### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by KarlDominic** [rstropek-teaching/real-time-game-quiz-4bhif-KarlDominic#1]
Mr. Stropek,

I am sorry but I did underestimate the workload and the time which was needed to develop my game and i won't be able to finish it till this thursday. But I will finish it befor thursday next week at the latest.

Regards,
Dominic Karl

**Comment by rstropek** [comment]
Thank you for letting me know. Try to work on the project until next week. It will be a great exercise for the exam.

Greetings,
Rainer Stropek.
